// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/shop": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/reseller": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/vs-viagra": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/shop" | "/about" | "/cart" | "/checkout" | "/contact" | "/faq" | "/login" | "/register" | "/reseller" | "/dashboard" | "/forgot-password" | "/reset-password" | "/vs-viagra";
  };
  "routes/Home.jsx": {
    id: "routes/Home";
    page: "/";
  };
  "routes/Shop.jsx": {
    id: "routes/Shop";
    page: "/shop";
  };
  "routes/About.jsx": {
    id: "routes/About";
    page: "/about";
  };
  "routes/Cart.jsx": {
    id: "routes/Cart";
    page: "/cart";
  };
  "routes/Checkout.jsx": {
    id: "routes/Checkout";
    page: "/checkout";
  };
  "routes/Contact.jsx": {
    id: "routes/Contact";
    page: "/contact";
  };
  "routes/FAQ.jsx": {
    id: "routes/FAQ";
    page: "/faq";
  };
  "routes/Login.jsx": {
    id: "routes/Login";
    page: "/login";
  };
  "routes/Register.jsx": {
    id: "routes/Register";
    page: "/register";
  };
  "routes/Reseller.jsx": {
    id: "routes/Reseller";
    page: "/reseller";
  };
  "routes/Dashboard.jsx": {
    id: "routes/Dashboard";
    page: "/dashboard";
  };
  "routes/ForgotPassword.jsx": {
    id: "routes/ForgotPassword";
    page: "/forgot-password";
  };
  "routes/ResetPassword.jsx": {
    id: "routes/ResetPassword";
    page: "/reset-password";
  };
  "routes/VaromaxVsViagra.jsx": {
    id: "routes/VaromaxVsViagra";
    page: "/vs-viagra";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/Home": typeof import("./app/routes/Home.jsx");
  "routes/Shop": typeof import("./app/routes/Shop.jsx");
  "routes/About": typeof import("./app/routes/About.jsx");
  "routes/Cart": typeof import("./app/routes/Cart.jsx");
  "routes/Checkout": typeof import("./app/routes/Checkout.jsx");
  "routes/Contact": typeof import("./app/routes/Contact.jsx");
  "routes/FAQ": typeof import("./app/routes/FAQ.jsx");
  "routes/Login": typeof import("./app/routes/Login.jsx");
  "routes/Register": typeof import("./app/routes/Register.jsx");
  "routes/Reseller": typeof import("./app/routes/Reseller.jsx");
  "routes/Dashboard": typeof import("./app/routes/Dashboard.jsx");
  "routes/ForgotPassword": typeof import("./app/routes/ForgotPassword.jsx");
  "routes/ResetPassword": typeof import("./app/routes/ResetPassword.jsx");
  "routes/VaromaxVsViagra": typeof import("./app/routes/VaromaxVsViagra.jsx");
};